"""Update log schema

Revision ID: f056e5a2084c
Revises: 7cbaf4c32299
Create Date: 2025-03-04 05:47:54.100252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f056e5a2084c'
down_revision: Union[str, None] = '7cbaf4c32299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('memory_usage', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('disk_io', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('network_traffic', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('failed_logins', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('connection_attempts', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('file_accesses', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('anomaly_detected', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('threat_level', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.drop_index('ix_logs_log_level', table_name='logs')
    op.drop_index('ix_logs_source', table_name='logs')
    op.create_index(op.f('ix_logs_event_type'), 'logs', ['event_type'], unique=False)
    op.drop_column('logs', 'source')
    op.drop_column('logs', 'message')
    op.drop_column('logs', 'log_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('log_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_logs_event_type'), table_name='logs')
    op.create_index('ix_logs_source', 'logs', ['source'], unique=False)
    op.create_index('ix_logs_log_level', 'logs', ['log_level'], unique=False)
    op.drop_column('logs', 'risk_score')
    op.drop_column('logs', 'threat_level')
    op.drop_column('logs', 'anomaly_detected')
    op.drop_column('logs', 'file_accesses')
    op.drop_column('logs', 'response_time')
    op.drop_column('logs', 'connection_attempts')
    op.drop_column('logs', 'failed_logins')
    op.drop_column('logs', 'network_traffic')
    op.drop_column('logs', 'disk_io')
    op.drop_column('logs', 'memory_usage')
    op.drop_column('logs', 'cpu_usage')
    op.drop_column('logs', 'event_type')
    # ### end Alembic commands ###
